/*
# Create store_orders table

1. Purpose
- Stores purchase orders submitted from the ULG CFW store.
- Each order gets a unique, human-readable order number (e.g. ULG-000001) generated by a sequence.

2. New Tables
- `store_orders`
  - `id` (uuid, primary key)
  - `order_number` (text, unique, not null)
  - `product_name` (text, not null)
  - `product_category` (text, nullable)
  - `price` (integer, not null)
  - `player_name` (text, not null)
  - `player_discord_id` (text, not null)
  - `payment_method` (text, not null) — visa, paypal, instapay, vodafone_cash
  - `status` (text, not null default 'pending')
  - `created_at` (timestamptz, default now())

3. New Sequence
- `store_orders_seq` — generates sequential order numbers.

4. Security
- RLS enabled on `store_orders`.
- No-auth public store: anon + authenticated can INSERT and SELECT.
- UPDATE/DELETE restricted to authenticated (staff).

5. Notes
- Order numbers generated as `ULG-` + zero-padded sequence value via trigger.
*/

CREATE SEQUENCE IF NOT EXISTS store_orders_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS store_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number text UNIQUE NOT NULL,
  product_name text NOT NULL,
  product_category text,
  price integer NOT NULL,
  player_name text NOT NULL,
  player_discord_id text NOT NULL,
  payment_method text NOT NULL CHECK (payment_method IN ('visa', 'paypal', 'instapay', 'vodafone_cash')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'cancelled', 'refunded')),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE store_orders ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION generate_store_order_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  next_val bigint;
BEGIN
  next_val := nextval('store_orders_seq');
  NEW.order_number := 'ULG-' || lpad(next_val::text, 6, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_store_order_number ON store_orders;
CREATE TRIGGER set_store_order_number
BEFORE INSERT ON store_orders
FOR EACH ROW
EXECUTE FUNCTION generate_store_order_number();

DROP POLICY IF EXISTS "anon_insert_store_orders" ON store_orders;
CREATE POLICY "anon_insert_store_orders" ON store_orders FOR INSERT
TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_select_store_orders" ON store_orders;
CREATE POLICY "anon_select_store_orders" ON store_orders FOR SELECT
TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "auth_update_store_orders" ON store_orders;
CREATE POLICY "auth_update_store_orders" ON store_orders FOR UPDATE
TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_store_orders" ON store_orders;
CREATE POLICY "auth_delete_store_orders" ON store_orders FOR DELETE
TO authenticated USING (true);
